sudo: false

addons:
    apt_packages:
        - lib32stdc++6

env:
  - SOURCEMOD_VERSION=1.10

before_install:
  - mkdir build-env

install:
  - cd build-env
  - SMPACKAGE="http://sourcemod.net/latest.php?os=linux&version=${SOURCEMOD_VERSION}"
  - wget $SMPACKAGE
  - tar -xzvf $(basename $SMPACKAGE)
  - cd addons/sourcemod/scripting/include
  - wget https://raw.githubusercontent.com/shavitush/bhoptimer/master/addons/sourcemod/scripting/include/shavit.inc
  - chmod 777 shavit.inc
  - cd ../../../../../
  - find build-env/addons/sourcemod/scripting/ -name "*.sp" -type f -delete
  - cp -rv addons/sourcemod/scripting/. build-env/addons/sourcemod/scripting/

before_script:
  - chmod +rx build-env/addons/sourcemod/scripting/spcomp
  - chmod +rx build-env/addons/sourcemod/scripting/compile.sh

script:
  - ./build-env/addons/sourcemod/scripting/compile.sh

before_deploy:
  - mkdir addons/sourcemod/plugins
  - cp -rv build-env/addons/sourcemod/scripting/compiled/. addons/sourcemod/plugins
  - rm -r build-env
  - zip -9rq release-$TRAVIS_COMMIT.zip addons

  - git config --local user.name "whocodes"
  - git config --local user.email "admin@whocodes.tech"
  - export TRAVIS_TAG=1.1.0-${TRAVIS_BUILD_NUMBER}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: "$APIKEY"
  file: "release-$TRAVIS_COMMIT.zip"
  name: Automatic Release $(date +'%m-%d-%Y %R')
  skip_cleanup: true